name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install jq
        run: sudo apt-get install jq

      - name: Install dependencies
        working-directory: ./functions
        run: |
          npm install -g firebase-tools
          npm install

      - name: Set up Firebase Admin credentials
        working-directory: ./functions
        run: |
          echo $FIREBASE_SERVICE_ACCOUNT_KEY | jq -r '.' > serviceAccountKey.json
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to Firebase Functions
        working-directory: ./functions
        run: firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}
